# Generated by Django 3.0.3 on 2020-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
                ('img', models.ImageField(upload_to='images')),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
